### ISSUE TITLE
fix: issue temnplate

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/v-taxi#14]
## description

1. 제목 양식이 없습니다.
2. 템플릿 이름이 없습니다. (현재 단일 종류입니다.)
3. Markdown 위계가 깨져있습니다. (알 수 없는 이유로 headings 2 부터 시작)
4. 본문이 인용구 처리가 되어있습니다.
5. 본문 heading 을 영문으로 유지한다면 대소문자 처리가 안 되어있습니다.

## to-do
- [ ] 작업1
- [ ] 작업2
- [ ] 작업3

**Comment by gong-yeongbin** [comment]
- 1. 제목 양식이 없습니다. > 타이틀에 fix: 이런식으로 표현되게 하면 될까요?
- 2. 템플릿 이름이 없습니다. (현재 단일 종류입니다.) > 커밋 메세지 타입 별로 만들면 될까요?

- 4. Markdown 위계가 깨져있습니다. (알 수 없는 이유로 headings 2 부터 시작)
- 5. 본문이 인용구 처리가 되어있습니다.
- 6. 본문 heading 을 영문으로 유지한다면 대소문자 처리가 안 되어있습니다.
> 4,5,6 수정하겠습니다

**Comment by kimseungbin** [comment]
> * 제목 양식이 없습니다. --> 타이틀에 fix: 이런식으로 표현되게 하면 될까요?

네 카테고리가 없습니다.


> * 템플릿 이름이 없습니다. (현재 단일 종류입니다.) --> 커밋 메세지 타입 별로 만들면 될까요?

전부 만들기에는 너무 많지 않을까요?

추가적으로 작업을 직접 진행하시는 것이라면, 시작 전 할일 목록을 수정해주세요.
