### ISSUE TITLE
feat: init Nest.js

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/v-taxi#2]
# 추가 기능

- nest cli 를 이용한 프로젝트 구성
  - swc builder 사용 (논의 필요)

# 할 일

- [x] Nest 세팅
- [x] `GET /` route 구현
- [x] #10

**Comment by XPECTER** [comment]
[SWC](https://docs.nestjs.com/recipes/swc)
SWC 빌더는 차후 의존성을 추가하면 되는 것으로 이해했습니다.
다른 이슈를 생성해서 거기서 설정할지, 지금 설정할지 정하면 좋을 것 같습니다.

**Comment by kimseungbin** [comment]
> 다른 이슈를 생성해서 거기서 설정할지, 지금 설정할지 정하면 좋을 것 같습니다.

1. 작업의 규모가 새 이슈가 필요할 정도로 큰 것인지
2. 현재 작업과 연속성이 있는지

두 부분이 궁금합니다.

**Comment by XPECTER** [comment]
1. 크기는 크지 않은 것으로 판단됩니다. 크게,
- 설치
- type check 설정
- JEST 설정
이 추가됩니다. Dynamo DB는 typeorm이 지원하지 않습니다.
2. 현재 작업과 연속하여 작업이 가능합니다.

**Comment by kimseungbin** [comment]
> 1. 크기는 크지 않은 것으로 판단됩니다. 크게,
> ...
> 2. 현재 작업에서 추가로 작업이 가능합니다.

그렇다면 바로 이어서 진행하시면 되지 않을까 싶습니다. 

> 별개로 문서화는 read me에 작성하는 것을 말씀하시는게 맞나요?

넵

**Comment by seanlion** [comment]
swc는 저도 한번도 안 써봤는데 이번 기회에 써보면 좋을 것 같네요. 세팅 감사합니다!
