### ISSUE TITLE
chore: Prettier&ESLint setting

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/v-taxi#3]
# 추가 기능

- 코드 포맷팅&린팅 도입

# 할 일

- [x] Prettier 설정
- [x] ESLint 설정
- [x] Formatting/Linting

# 레퍼런스

- #2 가 선행돼야함

**Comment by seanlion** [comment]
https://typescript-eslint.io/rules/semi/

rule의 기본값이 off인가요? rule 자체를 사용하지 않는걸 권장한다고 이해했는데, 사용하지 않으면 on이 되는 것인지..

**Comment by XPECTER** [comment]
'semi' 옵션의 기본값은 'error'입니다. 세미콜론을 빠뜨렸을 때 경고를 표시합니다.
'off'는 검사자체를 하지 않는 옵션입니다.
