### ISSUE TITLE
infra(GitHub): implement Continuous Integration

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/v-taxi#4]
# 추가 기능

- GitHub workflow 를 이용하여 CI 환경을 구축

# 할 일

- [x] 도커 이미지 빌드 스텝 추가
- [x] 테스트 코드 실행 스텝 추가
- [x] 포맷팅 검사 스텝 추가
- [x] 린팅 검사 스텝 추가
- [ ] 슬랙 알림 추가
- [x] 환경변수 설정

**Comment by seanlion** [comment]
도커 이미지 빌드 스텝 추가: compose up해서 pink healthcheck

환경변수 설정 : github secret, repository variable 설정

**Comment by gong-yeongbin** [comment]
#5 #6 이슈 완료후 진행으로 일정 변경
