### ISSUE TITLE
infra(Docker): Docker Compose

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/v-taxi#6]
# 추가 기능

- Docker Compose 를 도입하여 앱 실행 환경을 정의
  (논의) 우선적으로 development 환경의 변수를 Docker Compose 로 관리하는 방안

# 할 일

- [x] `docker-compose.yaml` 작성

**Comment by XPECTER** [comment]
> 우선적으로 development 환경의 변수를 Docker Compose 로 관리하는 방안
제가 이해한건, 일단 `development`일 때 환경변수는 `docker-compose.yml`에 하드 코딩으로 박아넣는 것인가요?
필요한 변수는 
- `APP_PORT`
- 컨테이너 `HOST_PORT`
이 두 개로 생각됩니다.

**Comment by kimseungbin** [comment]
하드코딩하면 안 될거같습니다. AWS parameter store 나 깃헙에 넣어놓으면 되지 않을까요?

**Comment by XPECTER** [comment]
네. PR로 올린 내용에는 github secrets를 사용하도록 작성했습니다.

**Comment by kimseungbin** [comment]
> 네. PR로 올린 내용에는 github secrets를 사용하도록 작성했습니다.

개발의 편의와 혼동을 막기 위해 암호화가 불필요한 정보를 GitHub Secrets 에 저장하는 것을 지양해주세요.
