### ISSUE TITLE
feat: Database

### ISSUE THREAD

**Issue by kimseungbin** [voyage-plus-1010/v-taxi#7]
# 논의 사항

1. DynamoDB 사용 여부
2. Database 테스트 방법
  1. Mocking 직접 구현
  2. DynamoDB local (official) for Docker 사용
  3. 기타...

# 추가 기능

# 할 일

**Comment by seanlion** [comment]
1.DynamoDB는 지난번 오프라인 모임때 사용해보자고 얘기했던 거로 기억납니다.
2.통합 테스트로 DynamoDB를 로컬 컨테이너에 설치해서 DB 테스트는 해볼 수 있을 것 같은데, 유닛 테스트 할때 DB 테스트를 해야할까요? 
(Repository 레이어 만들 경우 DB mock 구현해서 하는 건 봤습니다.)
자바 진영쪽에서는 Test Container라고 테스트 실행할 때마다 DB를 컨테이너로 띄웠다가 내리는 식으로 하는 것 같은데.. Node.js쪽에서는 비슷한 키워드를 아직 못 찾았습니다.
3. Mock DB를 구현할거면 Key,Value DB 형식으로 간단하게 구현하는게 좋을 것 같습니다.

**Comment by kimseungbin** [comment]
> 1.DynamoDB는 지난번 오프라인 모임때 사용해보자고 얘기했던 거로 기억납니다.

네 저도 DynamoDB 가 가장 적합하다고 생각하는데, 혹시 주말 간 다른 아이디어가 있으셨는지 궁금했습니다.


> 2.통합 테스트로 DynamoDB를 로컬 컨테이너에 설치해서 DB 테스트는 해볼 수 있을 것 같은데, 유닛 테스트 할때 DB 테스트를 해야할까요? (Repository 레이어 만들 경우 DB mock 구현해서 하는 건 봤습니다.) 자바 진영쪽에서는 Test Container라고 테스트 실행할 때마다 DB를 컨테이너로 띄웠다가 내리는 식으로 하는 것 같은데.. Node.js쪽에서는 비슷한 키워드를 아직 못 찾았습니다.

그럼 일단 "e2e 테스트는 도커 컨테이너를 사용한다" 고 가정하도록 하죠.
컨트롤러의 유닛 테스트의 경우 mock 하는 편이 좋다고 생각합니다.
서비스도 테스트를 할지는 모르겠네요. (한다면 이건 나중에 정하도록 하죠)

> 3. Mock DB를 구현할거면 Key,Value DB 형식으로 간단하게 구현하는게 좋을 것 같습니다.

좋습니다.

**Comment by XPECTER** [comment]
저도 Dynamo를 찾아보고 있었습니다. 테스트에 관해선 찾아보겠습니다.
